---
output: 
  html_document:
    toc: true
    toc_float: true
---

<link rel="stylesheet" href="styles.css" type="text/css">

## __Education__

***

### [<span style = "color:black">**Columbia University in the City of New York**</span>](https://www.columbia.edu)  
New York City, New York, the United States of America  
Expecting Graduation at April 2021  

* **GPA:** 3.82/4.00

[<span style = "color:black">_Master of Science, Biostatistics, Statistical Genetics track_</span>](https://www.publichealth.columbia.edu/academics/departments/biostatistics)  

* **Course Highlight:** Data Science I (tidy data), Biostatistical Methods I & II (logistic, linear mixed, and lasso regression models, cross validation), Statistical Inference, Statistical Genetic Modeling (GWAS, PCA, hierarchical clustering, k-means clustering, hierarchical clustering on principle components), Advanced Statistical and Computational Methods in Genetics and Genomics (SKAT, meta-analysis)

***

### [<span style = "color:black">**The University of Iowa**</span>](https://uiowa.edu/)               	   
Iowa City, Iowa, the United States of America  
January 2014 - May 2018  

* **GPA:** 3.77/4.00  
* **Dean’s List:** June 2014 – May 2018  

[<span style = "color:black">_Bachelor of Science, Statistics, Mathematical track_</span>](https://stat.uiowa.edu/)  
* __Course Highlight:__ Calculus, Linear Algebra, Statistical Methods and Computing (SAS and MATLAB), Bayesian Statistics (MCMC), Experimental Design and Analysis, Applied Linear Regression, Mathematical Statistics I & II, Computer Science I (Python)

[<span style = "color:black">_Bachelor of Arts, Asian Language and Studies, Japanese_</span>](https://asian-slavic.uiowa.edu/undergraduate-programs/japanese)   

* **Major GPA:** 4.03/4.00      
* **Course Highlight:** Japanese Linguistics, The Tale of Genji, Modern Japanese Literature Translation Workshop (We worked on the translation of one of her fictions, _the Great Outdoors_, with the author, Fujino Kaori in the workshop!)  

P.S. Please follow [<span style = "color:#4863A0">Fujino Kaori</span>](https://en.wikipedia.org/wiki/Kaori_Fujino), an awesome writer and person, on [<span style = "color:#4863A0">twitter</span>](https://twitter.com/fujinono) and [<span style = "color:#4863A0">instagram</span>](https://www.instagram.com/fujinono/?hl=en). 