---
---

<link rel="stylesheet" href="styles.css" type="text/css">

## **TEAM PROJECT**  

***

### **Exploring Vague Priors on a Variance Component in an LME Model**

* Followed up with Brain Smith’s research on PET images of cancer patient neck and head to investigate the influence of vague priors and the problem of how operators affect the average of the measurements
* Programmed and test ran in OpenBUGS and R with different priors for the variance component
* Present the findings in the form of an oral presentation and a written report 

***

### **Epigenome-wide Association Studies between DNA Methylation and Gastric Adenocarcinoma**

* Tidied and prepared data from The Cancer Genome Atlas database  on Gastric Adenocarcinoma
* Programmed in R using methods such as Principle Component Analysis to filter noise covariates, K-means Clustering to identify population substructure and association test to explore genes that associate with the onset of gastric cancer
* Used RMardown to draw conclusions based on the numerical results, deliver the result in visual aids, and interpreted the findings in the project to write a written report