---
output: 
  html_document:
    toc: true
    toc_float: true
---

<link rel="stylesheet" href="styles.css" type="text/css">

## __Work and Internship__

***

### __Data for Good Scholor__
__Herbert Irving Comprehensive Cancer Center, Columbia University in the City of New York, New York City, NY, USA__  
_October 2020 - Present_  

* Contribute as a biostatistical research assistant in Dr. Alison Taylor and Dr. Fatemeh Momen-Heravi's lab  
* Tidy, process, analysis and produce visual outputs for DNA methylation and microRNA data from TCGA head and neck cancer
* Utilize PCA, HCPC and GSEA to find miRNA, mRNA and DNA methylation clusters to interpret the function and expression in each cluster
* Collaborate in the project aims to identify molecular changes such as mutations and RNA signature of head and neck cancer in Black/African American and Hispanic minority populations with the goal of identifying novel therapies for cancer patients and reduce health disparities

***

### __Teaching Assistant__		 						              	      
__Columbia University in the City of New York, New York City, NY, USA__  
_August 2020 – Present_  

* Assist and mentor students in groups and on an individual basis for Introduction to Biostatistical Methods and Relational   Databases and SQL Programming  
* Communicate with students through emails and hold weekly office hours for Q&A sessions as well as review sessions  

***

### __Research Assistant__								                     
__Memorial Sloan Kettering Cancer Center, New York City, NY, USA__  
_June 2020 – Present_  

* Search, categorize and write literature summary by focused interests in the assigned topics  
* Work and collaborate on the handling effect and normalization methods of gastric cancer and sarcoma data from TCGA and collaborators  
* Attend weekly group meetings and communicate with members on related topics  
* Utilize R mainly with tidyverse, precision, TCGAbiolinks, Bioconductor packages to tidy, normalize and conduct analysis on TCGA dataset  

***

### __Instructor__  									          	          
__New Chanel, Changsha, Hunan, China__    
_January 2019 – August 2019_  

* Taught and facilitated 25-people daily classes and one-to-one individual sessions for GRE verbal courses, A-level courses, and AP courses in Statistics, Mathematics, Calculus, Computer Science and Economics  
* Aided program director to develop systematic evaluation questions and lesson planning  

***

### __Data Analyst__		  						      	        
__Hunan Television, Changsha, Hunan, China__    
_September 2018 – December 2018_   

* Analyzed, evaluated and examined data on real-time Nielsen ratings to deliver analysis and reports  
* Communicated and counseled with customers as well as supervisors on the advised prices predicted by logistic regression model for different commercials  
* Incorporated R into the data analysis process which enhanced the efficiency by about 20% compared to the old method  

***

### __Supplemental Instruction Leader__      			               
__Academic Resource Center, University of Iowa, Iowa City, IA, USA__  
_August 2016 - May 2018_  

* Mentored and led students to gain a deeper understanding of the subject which resulted in a 0.33 increase in GPA on average    
* Designed and facilitated the collaborative learning activities for small groups as well as large groups of students for 3 sessions per week during each semester  
* Assisted the hiring process of perspective Supplemental Instruction leaders by interviewing candidates  
* Completed monthly and biweekly administrative tasks on a time basis, such as attending meetings and writing a lesson plan  

***

### __Tippie Learning Coach Lead Tutor__                   
__Tippie College of Business, University of Iowa, Iowa City, IA, USA__  
_August 2015 – May 2018_  
* Aided program supervisor, other tutors, and faculty with biweekly outreach communications and meetings  
* Tailored Tippie Learning Coach experience to be a student-centered academic support program for larger lectures that contained over 300 students each semester  
* Modified and inspected the regulations for tutors as well as supervisors in the Tippie Learning Coach program  
* Empowered fellow tutors on redirecting questions and enhancing students’ performance by holding a workshop on the subject  
* Boosted the performances and grades of tutees  